//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGear_63131848.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebBanGear_63131848Entities : DbContext
    {
        public WebBanGear_63131848Entities()
            : base("name=WebBanGear_63131848Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    
        public virtual int TimKiemSP(string maSP, string tenSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemSP", maSPParameter, tenSPParameter);
        }
    
        public virtual int TimKiemDH(string maDH, string maND, string tenND)
        {
            var maDHParameter = maDH != null ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(string));
    
            var maNDParameter = maND != null ?
                new ObjectParameter("MaND", maND) :
                new ObjectParameter("MaND", typeof(string));
    
            var tenNDParameter = tenND != null ?
                new ObjectParameter("TenND", tenND) :
                new ObjectParameter("TenND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemDH", maDHParameter, maNDParameter, tenNDParameter);
        }
    
        public virtual int TimKiemND(string maND, string tenND)
        {
            var maNDParameter = maND != null ?
                new ObjectParameter("MaND", maND) :
                new ObjectParameter("MaND", typeof(string));
    
            var tenNDParameter = tenND != null ?
                new ObjectParameter("TenND", tenND) :
                new ObjectParameter("TenND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemND", maNDParameter, tenNDParameter);
        }
    
        public virtual int TimKiemCTDH(string maDH, string maSP, string tenSP)
        {
            var maDHParameter = maDH != null ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemCTDH", maDHParameter, maSPParameter, tenSPParameter);
        }
    
        public virtual int TimKiemLSP(string maLoaiSP, string tenLoai)
        {
            var maLoaiSPParameter = maLoaiSP != null ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemLSP", maLoaiSPParameter, tenLoaiParameter);
        }
    
        public virtual int TimKiemNCc(string maNCC, string tenNCC)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemNCc", maNCCParameter, tenNCCParameter);
        }
    }
}
