//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGear_63131848.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DonHangs = new HashSet<DonHang>();
        }

        public string MaNguoiDung { get; set; }
        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Bạn cần phải nhập họ tên của bạn")]
        public string HoTenND { get; set; }
        [Display(Name = "Tên tài khoản")]
        [Required(ErrorMessage = "Bạn cần phải nhập tên tài khoản của bạn")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Bạn cần phải nhập email của bạn")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Bạn cần phải nhập địa chỉ của bạn")]
        public string DiaChiND { get; set; }
        [Display(Name = "Mật khẩu")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bạn cần phải nhập mật khẩu của bạn")]
        public string MatKhau { get; set; }
        [Display(Name = "Xác nhận mật khẩu")]
        [DataType(DataType.Password)]
        [NotMapped]
        public string ReMatKhau { get; set; }
        public Nullable<int> MaQuyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
