//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGear_63131848.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [Display(Name = "Mã nhà cung cấp")]
        public string MaNCC { get; set; }
        [Display(Name = "Tên nhà cung cấp")]
        [Required(ErrorMessage = "Bạn cần phải nhập tên nhà cung cấp")]
        public string TenNCC { get; set; }
        [Display(Name = "Email nhà cung cấp")]
        [Required(ErrorMessage = "Bạn cần phải nhập email nhà cung cấp")]
        [EmailAddress]
        public string EmailNCC { get; set; }
        [Display(Name = "SĐT nhà cung cấp")]
        [Required(ErrorMessage = "Bạn cần phải nhập SĐT nhà cung cấp")]
        
        public string SDTNCC { get; set; }
        [Display(Name = "Địa chỉ nhà cung cấp")]
        [Required(ErrorMessage = "Bạn cần phải nhập địa chỉ nhà cung cấp")]
        public string DiaChiNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
